version: '3'

services:
  postgresdb:
    container_name: test_postgres
    platform: linux/x86_64
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  redisdb:
    container_name: test_redis
    image: redis
    restart: always
    volumes:
      - ./docker/redis:/data

  php-fpm:
    container_name: test_php
    image: npartyko/php-fpm:8.1
    restart: always
    volumes:
      - ./www:/var/www
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    working_dir: /var/www/laravel
    command: php artisan serve --host 0.0.0.0 --port=8000
    ports:
      - 8000:8000
    depends_on:
      - postgresdb
      - redisdb
